spring:
  datasource:
#    url: jdbc:mariadb://[your-mariadb-host]:3306/[your-database-name]
    driver-class-name: org.mariadb.jdbc.Driver
    username: [your-mariadb-username]
    password: [your-mariadb-password]
  jpa:
    hibernate:
      ddl-auto: validate
